// get public announces
export const GET_PUBLIC_ANNOUCE = "GET_PUBLIC_ANNOUCE";
export const GET_PUBLIC_ANNOUCE_SUCCESS = "GET_PUBLIC_ANNOUCE_SUCCESS";
export const GET_PUBLIC_ANNOUCE_FAIL = "GET_PUBLIC_ANNOUCE_FAIL";
// get private announce
export const GET_PRIVATE_ANNOUCE = "GET_PRIVATE_ANNOUCE";
export const GET_PRIVATE_ANNOUCE_SUCCESS = "GET_PRIVATE_ANNOUCE_SUCCESS";
export const GET_PRIVATE_ANNOUCE_FAIL = "GET_PRIVATE_ANNOUCE_FAIL";
