// get public announces
export const GET_PUBLIC_ANNOUCE = "GET_PUBLIC_ANNOUCE";
export const GET_PUBLIC_ANNOUCE_SUCCESS = "GET_PUBLIC_ANNOUCE_SUCCESS";
export const GET_PUBLIC_ANNOUCE_FAIL = "GET_PUBLIC_ANNOUCE_FAIL";
// get private announce
export const GET_PRIVATE_ANNOUCE = "GET_PRIVATE_ANNOUCE";
export const GET_PRIVATE_ANNOUCE_SUCCESS = "GET_PRIVATE_ANNOUCE_SUCCESS";
export const GET_PRIVATE_ANNOUCE_FAIL = "GET_PRIVATE_ANNOUCE_FAIL";
//get owner private announce //user announce
export const GET_PRIVATEUSER_ANNOUCE = "GET_PRIVATEUSER_ANNOUCE";
export const GET_PRIVATEUSER_ANNOUCE_SUCCESS = "GET_PRIVATEUSER_ANNOUCE_SUCCESS";
export const GET_PRIVATEUSER_ANNOUCE_FAIL = "GET_PRIVATEUSER_ANNOUCE_FAIL";

//get announce private by ID
export const GET_ANNOUCE_BYID = "GET_ANNOUCE_BYID";
export const GET_ANNOUCE_BYID_SUCCESS = "GET_ANNOUCE_BYID_SUCCESS";
export const GET_ANNOUCE_BYID_FAIL = "GET_ANNOUCE_BYID_FAIL";