// get public announces
export const GET_PUBLIC_ANNOUCE = "GET_PUBLIC_ANNOUCE";
export const GET_PUBLIC_ANNOUCE_SUCCESS = "GET_PUBLIC_ANNOUCE_SUCCESS";
export const GET_PUBLIC_ANNOUCE_FAIL = "GET_PUBLIC_ANNOUCE_FAIL";
// get private announce
export const GET_PRIVATE_ANNOUCE = "GET_PRIVATE_ANNOUCE";
export const GET_PRIVATE_ANNOUCE_SUCCESS = "GET_PRIVATE_ANNOUCE_SUCCESS";
export const GET_PRIVATE_ANNOUCE_FAIL = "GET_PRIVATE_ANNOUCE_FAIL";
//get owner private announce //user announce
export const GET_PRIVATEUSER_ANNOUCE = "GET_PRIVATEUSER_ANNOUCE";
export const GET_PRIVATEUSER_ANNOUCE_SUCCESS =
  "GET_PRIVATEUSER_ANNOUCE_SUCCESS";
export const GET_PRIVATEUSER_ANNOUCE_FAIL = "GET_PRIVATEUSER_ANNOUCE_FAIL";

//get announce private by ID
export const GET_ANNOUCE_BYID = "GET_ANNOUCE_BYID";
export const GET_ANNOUCE_BYID_SUCCESS = "GET_ANNOUCE_BYID_SUCCESS";
export const GET_ANNOUCE_BYID_FAIL = "GET_ANNOUCE_BYID_FAIL";
// post private announce
export const POST_ANNOUNCE = "POST_ANNOUNCE";
export const POST_ANNOUNCE_SUCCESS = "POST_ANNOUNCE_SUCCESS";
export const POST_ANNOUNCE_FAIL = "POST_ANNOUNCE_FAIL";
// Delete private announce
export const DELETE_ANNOUNCE_SUCCESS = "DELETE_ANNOUNCE_SUCCESS";
export const DELETE_ANNOUNCE_FAIL = "DELETE_ANNOUNCE_FAIL";
